/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MyUserRole = { 'teacher' : null } |
  { 'schoolAdmin' : null } |
  { 'student' : null } |
  { 'parent' : null };
export interface School {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'contactEmail' : string,
}
export interface StudentGroup {
  'id' : bigint,
  'name' : string,
  'schoolId' : bigint,
  'gradeLevel' : bigint,
}
export type Time = bigint;
export interface TutoringSession {
  'topic' : string,
  'studentId' : bigint,
  'subject' : string,
  'correctnessScore' : bigint,
  'understandingScore' : bigint,
  'timestamp' : Time,
}
export interface UserProfile {
  'id' : bigint,
  'principal' : Principal,
  'name' : string,
  'role' : MyUserRole,
  'email' : string,
  'groupId' : [] | [bigint],
  'schoolId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[bigint, string, bigint], bigint>,
  'createSchool' : ActorMethod<[string, string, string], bigint>,
  'createUserProfile' : ActorMethod<
    [Principal, string, string, MyUserRole, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroupsBySchool' : ActorMethod<[bigint], Array<StudentGroup>>,
  'getSchools' : ActorMethod<[], Array<School>>,
  'getStudentProgress' : ActorMethod<[bigint], Array<TutoringSession>>,
  'getStudentsByParent' : ActorMethod<[bigint], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyProgressSummary' : ActorMethod<
    [bigint],
    {
      'averageUnderstanding' : bigint,
      'averageCorrectness' : bigint,
      'sessionsCompleted' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkParentToStudent' : ActorMethod<[bigint, bigint], undefined>,
  'recordTutoringSession' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];