/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MyUserRole = IDL.Variant({
  'teacher' : IDL.Null,
  'schoolAdmin' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : MyUserRole,
  'email' : IDL.Text,
  'groupId' : IDL.Opt(IDL.Nat),
  'schoolId' : IDL.Opt(IDL.Nat),
});
export const StudentGroup = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'schoolId' : IDL.Nat,
  'gradeLevel' : IDL.Nat,
});
export const School = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const Time = IDL.Int;
export const TutoringSession = IDL.Record({
  'topic' : IDL.Text,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'correctnessScore' : IDL.Nat,
  'understandingScore' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createSchool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createUserProfile' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        MyUserRole,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroupsBySchool' : IDL.Func([IDL.Nat], [IDL.Vec(StudentGroup)], ['query']),
  'getSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'getStudentProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TutoringSession)],
      ['query'],
    ),
  'getStudentsByParent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyProgressSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'averageUnderstanding' : IDL.Nat,
          'averageCorrectness' : IDL.Nat,
          'sessionsCompleted' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkParentToStudent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'recordTutoringSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MyUserRole = IDL.Variant({
    'teacher' : IDL.Null,
    'schoolAdmin' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : MyUserRole,
    'email' : IDL.Text,
    'groupId' : IDL.Opt(IDL.Nat),
    'schoolId' : IDL.Opt(IDL.Nat),
  });
  const StudentGroup = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'schoolId' : IDL.Nat,
    'gradeLevel' : IDL.Nat,
  });
  const School = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const Time = IDL.Int;
  const TutoringSession = IDL.Record({
    'topic' : IDL.Text,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'correctnessScore' : IDL.Nat,
    'understandingScore' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createSchool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createUserProfile' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          MyUserRole,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroupsBySchool' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudentGroup)],
        ['query'],
      ),
    'getSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'getStudentProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TutoringSession)],
        ['query'],
      ),
    'getStudentsByParent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyProgressSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'averageUnderstanding' : IDL.Nat,
            'averageCorrectness' : IDL.Nat,
            'sessionsCompleted' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkParentToStudent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'recordTutoringSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };